### ISSUE TITLE
AddPackage DismProgressCallback - total 1000?

### ISSUE THREAD

**Issue by wingers999** [josemesona/ManagedDism#37] opened 2017-12-26 17:29 UTC
Any reason why total for the Progress Callback for AddPackage is out of a total of 1000? whereas as others seem to be 100 which works better for showing percentage done?

**Comment by Shidell** [comment] 2017-12-27 21:37
DISM_PROGRESS_CALLBACK is defined as DismProgressCallback(UINT Current, UINT Total, PVOID UserData). 

I haven't been able to find any reason why AddPackage might return "Total" out of 1000 (instead of 100), but if that is the case, all I can recommend is calculating a percentage based on Current/Total instead of implicitly trusting Current and Total will be out of 100.

My only guess is that any documentation on Current/Total being out of 1000 (or any value other than 100) is internal and based on the package state of the system and other packages--and might differ (other than X/100 or X/1000) in other DISM API functions (such as removing packages, mounting/unmounting images, etc.)

**Comment by wingers999** [comment] 2017-12-27 21:47
I have noticed on package it is out of a total of 1000 and it seems for unmounts it sometimes is out of 200 - so varies depending on command it seems - not a problem as you say as just set my progress bar to correct total and show value based on that

**Comment by Shidell** [comment] 2017-12-27 21:58
I can say that with respect to unmounting packages, I do believe that the first 100 represents committing changes--either committing them, discarding them--while the last 100 actually represents the "unmounting" process itself.

I'll look into it a bit more to see if perhaps something else could be done to make it more transparent to the caller (e.g. "Hey, during an unmount, the first 100 is committing/discarding changes, whilst the last 100 is the actual unmount operation"), but I think it may be a bit of a stumbling block in that the native API behaves this way, and to preserve the native-managed 1:1 mapping of this wrapper, modifying the DismApi code would break that 1:1 preservation. However, perhaps something in a "Utilities" class might be possible, and I just submitted a pull request (that @josemesona and I have talked about previously) to add a "DismUtilities" class, and this type of feature (and "/recurse", and others), might fit nicely in, if @josemesona approves.

**Comment by wingers999** [comment] 2017-12-27 22:00
that definitely makes perfect sense to me - hadn't thought of it like that :)

**Comment by Shidell** [comment] 2017-12-27 22:06
Yeah, it's a "gotcha" that the API isn't real forthcoming about (the native API, I mean.)

Perhaps the best solution would be to modify the managed API comments to simply explain these situations--for example, that the return "Total" value may be out of 200 (instead of 100), and if so, to handle the return progress appropriately (if the caller cares to report "committing/discarding" vs. "unmounting".)

Do you happen to know if it only returns out of 200 when unmounting an image that hasn't been "committed" or "discarded"? If it's out of 100 after committed/discarded, and out of 200 when neither has been performed, I think that would close the book on progress (at least for "unmounting.") Adding/removing Packages is another story.

**Comment by wingers999** [comment] 2017-12-27 22:11
just ran a quick test and it seems for /discard it is 100 and for commit it is 200 - which makes sense now

**Comment by Shidell** [comment] 2017-12-27 22:18
So if you make a change, and then do "unmount", it's 200?

And if you make a change, and then do either a "commit" or a "discard", and then "unmount", it's 100?

**Comment by wingers999** [comment] 2017-12-27 22:20
if you unmount and set commitchanges to true then it is 200
if you unmount and set commitchanges to false then it is 100

So as you say first 100 would be changes being committed and then second 100 the unmount operation perhaps

**Comment by Shidell** [comment] 2017-12-27 22:22
Okay, that makes sense.

If you make a change, and first call DismApi.CommitImage() (committing or discarding), and then call DismApi.UnmountImage() (committing or discarding), it should always be 100. 

Can you verify that as well?

**Comment by wingers999** [comment] 2017-12-27 22:30
I will give that a try when I get a moment and let you know
On a separate note - something you may have answer too - do you know of a API for using DiskPart in VB / C# .NET - or an equivalent?

**Comment by Shidell** [comment] 2017-12-27 22:33
Sorry, I'm not familiar with a library to wrap DiskPart off the top of my head.

**Comment by jeffkl** [comment] 2018-06-26 15:50
I'm closing this as by design.  I did some tests and it seems like the "total" is what you can expect the "count" to be when its done.  In my testing, current started at 50 while total was 1000 and current eventually got to 1000.  In other cases it started at 10 and went to 200.  I wish it was more documented.

**Closed by jeffkl** 2018-06-26 15:50 UTC
